import { IProduct, IPost, IUser } from './types';

export const testPost: IPost = {
  id: 1,
  title: 'His mother had always taught him',
  body: "His mother had always taught him not to ever think of himself as better than others. He'd tried to live by this motto. He never looked down on those who were less fortunate or who had less money than him. But the stupidity of the group of people he was talking to made him change his mind.",
  userId: 9,
  tags: ['history', 'american', 'crime'],
  reactions: 2,
};

// An example of a test user
export const testUser: IUser = {
  id: 1,
  firstName: 'Terry',
  lastName: 'Medhurst',
  maidenName: 'Smitham',
  phone: '+63 791 675 8914',
  username: 'atuny0',
  // password:"9uQFF1Lh",
  image: 'https://robohash.org/hicveldicta.png',
  domain: 'slashdot.org',
};

export const testProduct: IProduct = {
  id: 1,
  title: 'iPhone 9',
  description: 'An apple mobile which is nothing like apple',
  price: 549,
  discountPercentage: 12.96,
  rating: 4.69,
  stock: 94,
  brand: 'Apple',
  category: 'smartphones',
  thumbnail: 'https://i.dummyjson.com/data/products/1/thumbnail.jpg',
  images: [
    'https://i.dummyjson.com/data/products/1/1.jpg',
    'https://i.dummyjson.com/data/products/1/2.jpg',
    'https://i.dummyjson.com/data/products/1/3.jpg',
    'https://i.dummyjson.com/data/products/1/4.jpg',
    'https://i.dummyjson.com/data/products/1/thumbnail.jpg',
  ],
};

export const testCart = {
  skip: 0,
  limit: 20,
  products: {
    items: [
      {
        id: 1,
        products: [
          {
            id: 59,
            title: 'Spring and summershoes',
            price: 20,
            quantity: 3,
            total: 60,
            discountPercentage: 8.71,
            discountedPrice: 55,
            brand: 'Apple',
            category: 'smartphones',
            thumbnail:
              'https://i.dummyjson.com/data/products/1/thumbnail.jpg',
          },
          {
            id: 88,
            title: 'TC Reusable Silicone Magic Washing Gloves',
            price: 29,
            quantity: 2,
            total: 58,
            discountPercentage: 3.19,
            discountedPrice: 56,
            brand: 'Tesla',
            category: 'smartphones',
            thumbnail:
              'https://i.dummyjson.com/data/products/1/thumbnail.jpg',
          },
          {
            id: 18,
            title: 'Oil Free Moisturizer 100ml',
            price: 40,
            quantity: 2,
            total: 80,
            discountPercentage: 13.1,
            discountedPrice: 70,
            brand: 'Apple',
            category: 'smartphones',
            thumbnail:
              'https://i.dummyjson.com/data/products/1/thumbnail.jpg',
          },
          {
            id: 95,
            title: 'Wholesale cargo lashing Belt',
            price: 930,
            quantity: 1,
            total: 930,
            discountPercentage: 17.67,
            discountedPrice: 766,
            brand: 'Apple',
            category: 'smartphones',
            thumbnail:
              'https://i.dummyjson.com/data/products/1/thumbnail.jpg',
          },
          {
            id: 39,
            title: 'Women Sweaters Wool',
            price: 600,
            quantity: 2,
            total: 1200,
            discountPercentage: 17.2,
            discountedPrice: 994,
            brand: 'Apple',
            category: 'smartphones',
            thumbnail:
              'https://i.dummyjson.com/data/products/1/thumbnail.jpg',
          },
        ],
        total: 2328,
        discountedTotal: 1941,
        userId: 97,
        totalProducts: 5,
        totalQuantity: 10,
      },
      {
        id: 2,
        products: [
          {
            id: 96,
            title: 'lighting ceiling kitchen',
            price: 30,
            quantity: 2,
            total: 60,
            discountPercentage: 14.89,
            discountedPrice: 51,
            brand: 'Apple',
            category: 'smartphones',
            thumbnail:
              'https://i.dummyjson.com/data/products/1/thumbnail.jpg',
          },
          {
            id: 91,
            title: 'Black Motorbike',
            price: 569,
            quantity: 3,
            total: 1707,
            discountPercentage: 13.63,
            discountedPrice: 1474,
            brand: 'Apple',
            category: 'smartphones',
            thumbnail:
              'https://i.dummyjson.com/data/products/1/thumbnail.jpg',
          },
          {
            id: 9,
            title: 'Infinix INBOOK',
            price: 1099,
            quantity: 1,
            total: 1099,
            discountPercentage: 11.83,
            discountedPrice: 969,
            brand: 'Apple',
            category: 'smartphones',
            thumbnail:
              'https://i.dummyjson.com/data/products/1/thumbnail.jpg',
          },
          {
            id: 16,
            title: 'Hyaluronic Acid Serum',
            price: 19,
            quantity: 1,
            total: 19,
            discountPercentage: 13.31,
            discountedPrice: 16,
            brand: 'Apple',
            category: 'smartphones',
            thumbnail:
              'https://i.dummyjson.com/data/products/1/thumbnail.jpg',
          },
          {
            id: 54,
            title: 'Pubg Printed Graphic T-Shirt',
            price: 46,
            quantity: 3,
            total: 138,
            discountPercentage: 16.44,
            discountedPrice: 115,
            brand: 'Apple',
            category: 'smartphones',
            thumbnail:
              'https://i.dummyjson.com/data/products/1/thumbnail.jpg',
          },
        ],
        total: 3023,
        discountedTotal: 2625,
        userId: 30,
        totalProducts: 5,
        totalQuantity: 10,
      },
      {
        id: 3,
        products: [
          {
            id: 37,
            title: 'ank Tops for Womens/Girls',
            price: 50,
            quantity: 2,
            total: 100,
            discountPercentage: 12.05,
            discountedPrice: 88,
            brand: 'Apple',
            category: 'smartphones',
            thumbnail:
              'https://i.dummyjson.com/data/products/1/thumbnail.jpg',
          },
          {
            id: 80,
            title: 'Chain Pin Tassel Earrings',
            price: 45,
            quantity: 3,
            total: 135,
            discountPercentage: 17.75,
            discountedPrice: 111,
            brand: 'Apple',
            category: 'smartphones',
            thumbnail:
              'https://i.dummyjson.com/data/products/1/thumbnail.jpg',
          },
          {
            id: 68,
            title: 'Stylish Luxury Digital Watch',
            price: 57,
            quantity: 3,
            total: 171,
            discountPercentage: 9.03,
            discountedPrice: 156,
            brand: 'Apple',
            category: 'smartphones',
            thumbnail:
              'https://i.dummyjson.com/data/products/1/thumbnail.jpg',
          },
          {
            id: 81,
            title: 'Round Silver Frame Sun Glasses',
            price: 19,
            quantity: 1,
            total: 19,
            discountPercentage: 10.1,
            discountedPrice: 17,
            brand: 'Apple',
            category: 'smartphones',
            thumbnail:
              'https://i.dummyjson.com/data/products/1/thumbnail.jpg',
          },
          {
            id: 90,
            title: 'Cycle Bike Glow',
            price: 35,
            quantity: 1,
            total: 35,
            discountPercentage: 11.08,
            discountedPrice: 31,
            brand: 'Apple',
            category: 'smartphones',
            thumbnail:
              'https://i.dummyjson.com/data/products/1/thumbnail.jpg',
          },
        ],
        total: 460,
        discountedTotal: 403,
        userId: 63,
        totalProducts: 5,
        totalQuantity: 10,
      },
      {
        id: 4,
        products: [
          {
            id: 36,
            title: 'Sleeve Shirt Womens',
            price: 90,
            quantity: 1,
            total: 90,
            discountPercentage: 10.89,
            discountedPrice: 80,
            brand: 'Apple',
            category: 'smartphones',
            thumbnail:
              'https://i.dummyjson.com/data/products/1/thumbnail.jpg',
          },
          {
            id: 54,
            title: 'Pubg Printed Graphic T-Shirt',
            price: 46,
            quantity: 1,
            total: 46,
            discountPercentage: 16.44,
            discountedPrice: 38,
            brand: 'Apple',
            category: 'smartphones',
            thumbnail:
              'https://i.dummyjson.com/data/products/1/thumbnail.jpg',
          },
          {
            id: 11,
            title: 'perfume Oil',
            price: 13,
            quantity: 3,
            total: 39,
            discountPercentage: 8.4,
            discountedPrice: 36,
            brand: 'Apple',
            category: 'smartphones',
            thumbnail:
              'https://i.dummyjson.com/data/products/1/thumbnail.jpg',
          },
          {
            id: 47,
            title: 'Sneaker shoes',
            price: 120,
            quantity: 2,
            total: 240,
            discountPercentage: 10.37,
            discountedPrice: 215,
            brand: 'Apple',
            category: 'smartphones',
            thumbnail:
              'https://i.dummyjson.com/data/products/1/thumbnail.jpg',
          },
          {
            id: 64,
            title: 'Leather Strap Skeleton Watch',
            price: 46,
            quantity: 3,
            total: 138,
            discountPercentage: 10.2,
            discountedPrice: 124,
            brand: 'Apple',
            category: 'smartphones',
            thumbnail:
              'https://i.dummyjson.com/data/products/1/thumbnail.jpg',
          },
        ],
        total: 553,
        discountedTotal: 493,
        userId: 83,
        totalProducts: 5,
        totalQuantity: 10,
      },
    ],
    limit: 0,
    skip: 20,
    total: 40,
  },
  summary: {
    subtotal: 80.33,
    tax: 10,
    total: 90.33,
  },
};

export const testCartBackUp = {
  skip: 0,
  limit: 20,
  products: {
    items: [
      {
        id: 1,
        products: [
          {
            id: 59,
            title: 'Spring and summershoes',
            price: 20,
            quantity: 3,
            total: 60,
            discountPercentage: 8.71,
            discountedPrice: 55,
            brand: 'Apple',
            category: 'smartphones',
            thumbnail:
              'https://i.dummyjson.com/data/products/1/thumbnail.jpg',
          },
          {
            id: 88,
            title: 'TC Reusable Silicone Magic Washing Gloves',
            price: 29,
            quantity: 2,
            total: 58,
            discountPercentage: 3.19,
            discountedPrice: 56,
            brand: 'Tesla',
            category: 'smartphones',
            thumbnail:
              'https://i.dummyjson.com/data/products/1/thumbnail.jpg',
          },
          {
            id: 18,
            title: 'Oil Free Moisturizer 100ml',
            price: 40,
            quantity: 2,
            total: 80,
            discountPercentage: 13.1,
            discountedPrice: 70,
            brand: 'Apple',
            category: 'smartphones',
            thumbnail:
              'https://i.dummyjson.com/data/products/1/thumbnail.jpg',
          },
          {
            id: 95,
            title: 'Wholesale cargo lashing Belt',
            price: 930,
            quantity: 1,
            total: 930,
            discountPercentage: 17.67,
            discountedPrice: 766,
            brand: 'Apple',
            category: 'smartphones',
            thumbnail:
              'https://i.dummyjson.com/data/products/1/thumbnail.jpg',
          },
          {
            id: 39,
            title: 'Women Sweaters Wool',
            price: 600,
            quantity: 2,
            total: 1200,
            discountPercentage: 17.2,
            discountedPrice: 994,
            brand: 'Apple',
            category: 'smartphones',
            thumbnail:
              'https://i.dummyjson.com/data/products/1/thumbnail.jpg',
          },
        ],
        total: 2328,
        discountedTotal: 1941,
        userId: 97,
        totalProducts: 5,
        totalQuantity: 10,
      },
      {
        id: 2,
        products: [
          {
            id: 96,
            title: 'lighting ceiling kitchen',
            price: 30,
            quantity: 2,
            total: 60,
            discountPercentage: 14.89,
            discountedPrice: 51,
            brand: 'Apple',
            category: 'smartphones',
            thumbnail:
              'https://i.dummyjson.com/data/products/1/thumbnail.jpg',
          },
          {
            id: 91,
            title: 'Black Motorbike',
            price: 569,
            quantity: 3,
            total: 1707,
            discountPercentage: 13.63,
            discountedPrice: 1474,
            brand: 'Apple',
            category: 'smartphones',
            thumbnail:
              'https://i.dummyjson.com/data/products/1/thumbnail.jpg',
          },
          {
            id: 9,
            title: 'Infinix INBOOK',
            price: 1099,
            quantity: 1,
            total: 1099,
            discountPercentage: 11.83,
            discountedPrice: 969,
            brand: 'Apple',
            category: 'smartphones',
            thumbnail:
              'https://i.dummyjson.com/data/products/1/thumbnail.jpg',
          },
          {
            id: 16,
            title: 'Hyaluronic Acid Serum',
            price: 19,
            quantity: 1,
            total: 19,
            discountPercentage: 13.31,
            discountedPrice: 16,
            brand: 'Apple',
            category: 'smartphones',
            thumbnail:
              'https://i.dummyjson.com/data/products/1/thumbnail.jpg',
          },
          {
            id: 54,
            title: 'Pubg Printed Graphic T-Shirt',
            price: 46,
            quantity: 3,
            total: 138,
            discountPercentage: 16.44,
            discountedPrice: 115,
            brand: 'Apple',
            category: 'smartphones',
            thumbnail:
              'https://i.dummyjson.com/data/products/1/thumbnail.jpg',
          },
        ],
        total: 3023,
        discountedTotal: 2625,
        userId: 30,
        totalProducts: 5,
        totalQuantity: 10,
      },
      {
        id: 3,
        products: [
          {
            id: 37,
            title: 'ank Tops for Womens/Girls',
            price: 50,
            quantity: 2,
            total: 100,
            discountPercentage: 12.05,
            discountedPrice: 88,
            brand: 'Apple',
            category: 'smartphones',
            thumbnail:
              'https://i.dummyjson.com/data/products/1/thumbnail.jpg',
          },
          {
            id: 80,
            title: 'Chain Pin Tassel Earrings',
            price: 45,
            quantity: 3,
            total: 135,
            discountPercentage: 17.75,
            discountedPrice: 111,
            brand: 'Apple',
            category: 'smartphones',
            thumbnail:
              'https://i.dummyjson.com/data/products/1/thumbnail.jpg',
          },
          {
            id: 68,
            title: 'Stylish Luxury Digital Watch',
            price: 57,
            quantity: 3,
            total: 171,
            discountPercentage: 9.03,
            discountedPrice: 156,
            brand: 'Apple',
            category: 'smartphones',
            thumbnail:
              'https://i.dummyjson.com/data/products/1/thumbnail.jpg',
          },
          {
            id: 81,
            title: 'Round Silver Frame Sun Glasses',
            price: 19,
            quantity: 1,
            total: 19,
            discountPercentage: 10.1,
            discountedPrice: 17,
            brand: 'Apple',
            category: 'smartphones',
            thumbnail:
              'https://i.dummyjson.com/data/products/1/thumbnail.jpg',
          },
          {
            id: 90,
            title: 'Cycle Bike Glow',
            price: 35,
            quantity: 1,
            total: 35,
            discountPercentage: 11.08,
            discountedPrice: 31,
            brand: 'Apple',
            category: 'smartphones',
            thumbnail:
              'https://i.dummyjson.com/data/products/1/thumbnail.jpg',
          },
        ],
        total: 460,
        discountedTotal: 403,
        userId: 63,
        totalProducts: 5,
        totalQuantity: 10,
      },
      {
        id: 4,
        products: [
          {
            id: 36,
            title: 'Sleeve Shirt Womens',
            price: 90,
            quantity: 1,
            total: 90,
            discountPercentage: 10.89,
            discountedPrice: 80,
            brand: 'Apple',
            category: 'smartphones',
            thumbnail:
              'https://i.dummyjson.com/data/products/1/thumbnail.jpg',
          },
          {
            id: 54,
            title: 'Pubg Printed Graphic T-Shirt',
            price: 46,
            quantity: 1,
            total: 46,
            discountPercentage: 16.44,
            discountedPrice: 38,
            brand: 'Apple',
            category: 'smartphones',
            thumbnail:
              'https://i.dummyjson.com/data/products/1/thumbnail.jpg',
          },
          {
            id: 11,
            title: 'perfume Oil',
            price: 13,
            quantity: 3,
            total: 39,
            discountPercentage: 8.4,
            discountedPrice: 36,
            brand: 'Apple',
            category: 'smartphones',
            thumbnail:
              'https://i.dummyjson.com/data/products/1/thumbnail.jpg',
          },
          {
            id: 47,
            title: 'Sneaker shoes',
            price: 120,
            quantity: 2,
            total: 240,
            discountPercentage: 10.37,
            discountedPrice: 215,
            brand: 'Apple',
            category: 'smartphones',
            thumbnail:
              'https://i.dummyjson.com/data/products/1/thumbnail.jpg',
          },
          {
            id: 64,
            title: 'Leather Strap Skeleton Watch',
            price: 46,
            quantity: 3,
            total: 138,
            discountPercentage: 10.2,
            discountedPrice: 124,
            brand: 'Apple',
            category: 'smartphones',
            thumbnail:
              'https://i.dummyjson.com/data/products/1/thumbnail.jpg',
          },
        ],
        total: 553,
        discountedTotal: 493,
        userId: 83,
        totalProducts: 5,
        totalQuantity: 10,
      },
    ],
    limit: 0,
    skip: 20,
    total: 40,
  },
  summary: {
    subtotal: 80.33,
    tax: 10,
    total: 90.33,
  },
};
